env:
  es2021: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
extends:
  - 'airbnb-base'
rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
